version: '0.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release
  - Debug

install:
    - git submodule update --init --recursive

before_build:
    - cmd: |-
        mkdir build
        cd build
        cmake --version
        cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=install
        dir

build:
  project: $(APPVEYOR_BUILD_FOLDER)/build/$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - echo '%APPVEYOR_BUILD_FOLDER%\\%CONFIGURATION%\\tests.exe'

