version: '0.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release

install:
    - echo "Done clone here"

before_build:
    - cmd: |-
        mkdir build
        cd build
        cmake --version
        cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=install
        cmake --build . --target package --config Release

build_script:
    - echo "Done"

after_build:
    - cmd: |-
        cd %APPVEYOR_BUILD_FOLDER%\build
        dir /s /b

test_script:
  - echo '%APPVEYOR_BUILD_FOLDER%\\%CONFIGURATION%\\tests.exe'

artifacts:
    - path: build/deploy

deploy:
    provider: GitHub
    auth_token:
        secure: HHPH5otHDTeP2iU11PdRWnhpOMycDJ/n+NKC0xvSphvA4NLz41/rASWc1UseTQgU
    on:
        APPVEYOR_REPO_TAG: true
