version: '0.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release
  - Debug

install:
    - echo "Done clone here"

before_build:
    - cmd: |-
        mkdir build
        cd build
        cmake --version
        cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=install
        cmake --build . --target install

after_build:
    - cmd: |-
        cd %APPVEYOR_BUILD_FOLDER%\build
        dir /s /b

test_script:
  - echo '%APPVEYOR_BUILD_FOLDER%\\%CONFIGURATION%\\tests.exe'

